  version: "3.3"
  services:
    es01:
      restart: always
      image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
      container_name: es01
      hostname: es01
      environment:
        - node.name=es01
        - cluster.name=es-docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - http.port=9200
        - transport.profiles.default.port=9300
        - discovery.type=single-node
        - "ELASTIC_PASSWORD=Gcalls2020#"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - ./data/es01:/usr/share/elasticsearch/data:rw
        - ./backups:/usr/backups:rw
        - ./config/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
      ports:
        - 9300:9300
        - 9200:9200

    logstash:
      restart: always
      container_name: logstash
      image:  registry.gitlab.com/gcalls/devops/development/logstash
      volumes:
        - ./pipelines-prod:/usr/share/logstash/pipeline:ro
        - ./config/pipelines-prod.yml:/usr/share/logstash/config/pipelines.yml:ro
      ports:
        - "5000:5000"
        - "9600:9600"
        - "7002:7002"
        - "3019:3019"
        - "3020:3020"
        - "5044:5044"
        - "8081:8081"
      environment:
        - ELASTICSEARCH_HOSTS=["http://es01:9200"]
        - xpack.monitoring.elasticsearch.hosts=["http://es01:9200"]
        - XPACK_MONITORING_ENABLED=true
        - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
        - log.level=info
        - xpack.monitoring.elasticsearch.username=elastic
        - xpack.monitoring.elasticsearch.password=Gcalls2020#
        - xpack.management.elasticsearch.username=elastic
        - xpack.management.elasticsearch.password=Gcalls2020#
      ulimits:
        memlock:
          soft: -1
          hard: -1
      depends_on:
        - es01
        
    kibana:
      restart: always
      container_name: kibana
      image:  docker.elastic.co/kibana/kibana:7.7.0
      ports:
        - "5601:5601"
      environment:
        ELASTICSEARCH_HOSTS: http://es01:9200
      volumes:
        - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
      depends_on:
        - es01

