cluster.name: "es-docker-cluster"
network.host: 0.0.0.0
path.repo: ["/usr/backups/elastic"]
xpack.license.self_generated.type: basic
xpack.monitoring.enabled: true
xpack.security.enabled: true
cluster.routing.allocation.disk.threshold_enabled: false
discovery.type: single-node
