# Kibana is served by a back end server. This setting specifies the port to use.
server.port: 5601
server.host: "0.0.0.0"
elasticsearch.hosts: ["http://es01:9200"]
kibana.index: ".kibana"
elasticsearch.username: "elastic"
elasticsearch.password: "test#123"
elasticsearch.startupTimeout: 5000
elasticsearch.logQueries: false
# logging.dest: /var/log/kibana/kibana.log
logging.verbose: false
xpack.security.encryptionKey: "something_at_least_32_characters"
xpack.encryptedSavedObjects.encryptionKey: "something_at_least_32_characters"
